---
title: "Kernel Ridge Regression"
output: github_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("knitr")
library("stringr")
model_name <- "KRR"
dir_name   <- "~/Dropbox/Quimica/Docker/docker-solubility/data_analysis/built_models/"
short_name <- gsub(" ","",model_name)
model_dir  <- gsub(" ", "_", tolower(model_name))
model_path <- paste0(dir_name,model_dir)
  
knitr::opts_knit$set(root.dir = model_path)

library("ggplot2")
library("reshape2")
library("grid")
library("gridExtra")

#extract legend
#https://github.com/hadley/ggplot2/wiki/Share-a-legend-between-two-ggplot2-graphs
g_legend<-function(a.gplot){
  tmp <- ggplot_gtable(ggplot_build(a.gplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)}
```

## Model Description
Here goes the model explanation

## Model metrics

Several models were fitted to asses convergence. R² was used as the model's metric. 

```{r}
analysis  <- read.csv(paste0(model_path,"/",model_name,"Analysis.csv"))
kable(analysis)
```

The following kernel_density compares the errors in both the training and the validation sets:

```{r, echo = FALSE}

vval_pred  <- read.csv(paste0(model_path,"/predict_train.csv"))
tval_pred  <- read.csv(paste0(model_path,"/predict_validation.csv"))

#Get original data
vval_original <- read.csv(paste0(model_path,"/valid_original.csv"))
tval_original <- read.csv(paste0(model_path,"/train_original.csv"))

#Errors
validation_errors <- vval_original$prediction - vval_pred$prediction
train_errors      <- tval_original$prediction - tval_pred$prediction
summary_valid <- summary(validation_errors)
summary_train <- summary(train_errors)
summary_valid_abs <- summary(abs(validation_errors))
summary_train_abs <- summary(abs(train_errors))
summary_df    <- as.data.frame(cbind(summary_train, summary_train_abs, summary_valid, summary_valid_abs))
colnames(summary_df) <- c("Train errors", "Absolute Train errors", "Validation errors", "Absolute Validation errors")

kable(summary_df)
```
 
```{r, echo = FALSE}
validation_errors <- as.data.frame(validation_errors)
train_errors      <- as.data.frame(train_errors)
colnames(validation_errors) <- c("errors")
colnames(train_errors) <- c("errors")
validation_errors$type <- "Validation"
train_errors$type <- "Train"
ggplot(rbind(validation_errors, train_errors)) + geom_density(aes(x = errors, color = type)) +
  theme_bw() + ggtitle("Error:\nPredicted log solubility - Experimental log solubility")
```
## Example
You can run the model via the following command:

```{r results='markup', echo = FALSE, comment=NA}
dcommand <- paste0("docker run --rm -v ~/PATH/TO_FILE/YOU_WANT_TO_WORK_ON/:/data docker-solubility ", short_name)
cat(noquote(dcommand))
```


## See also
- [User's manual](https://github.com/RodrigoZepeda/docker-solubility/blob/master/Manual.md)
- [README](https://github.com/RodrigoZepeda/docker-solubility/blob/master/README.md)

